// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.ultimate.reportbuilder.reporting_bridge_flutter;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class ThermalPrinterApi {
  static boolean pigeonDoubleEquals(double a, double b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0 ? 0.0 : a) == (b == 0.0 ? 0.0 : b) || (Double.isNaN(a) && Double.isNaN(b));
  }

  static boolean pigeonFloatEquals(float a, float b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0f ? 0.0f : a) == (b == 0.0f ? 0.0f : b) || (Float.isNaN(a) && Float.isNaN(b));
  }

  static int pigeonDoubleHashCode(double d) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (d == 0.0) {
      d = 0.0;
    }
    long bits = Double.doubleToLongBits(d);
    return (int) (bits ^ (bits >>> 32));
  }

  static int pigeonFloatHashCode(float f) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (f == 0.0f) {
      f = 0.0f;
    }
    return Float.floatToIntBits(f);
  }

  static boolean pigeonDeepEquals(Object a, Object b) {
    if (a == b) { return true; }
    if (a == null || b == null) { return false; }
    if (a instanceof byte[] && b instanceof byte[]) {
      return Arrays.equals((byte[]) a, (byte[]) b);
    }
    if (a instanceof int[] && b instanceof int[]) {
      return Arrays.equals((int[]) a, (int[]) b);
    }
    if (a instanceof long[] && b instanceof long[]) {
      return Arrays.equals((long[]) a, (long[]) b);
    }
    if (a instanceof double[] && b instanceof double[]) {
      double[] da = (double[]) a;
      double[] db = (double[]) b;
      if (da.length != db.length) {
        return false;
      }
      for (int i = 0; i < da.length; i++) {
        if (!pigeonDoubleEquals(da[i], db[i])) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof List && b instanceof List) {
      List<?> listA = (List<?>) a;
      List<?> listB = (List<?>) b;
      if (listA.size() != listB.size()) { return false; }
      for (int i = 0; i < listA.size(); i++) {
        if (!pigeonDeepEquals(listA.get(i), listB.get(i))) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Map && b instanceof Map) {
      Map<?, ?> mapA = (Map<?, ?>) a;
      Map<?, ?> mapB = (Map<?, ?>) b;
      if (mapA.size() != mapB.size()) { return false; }
      for (Map.Entry<?, ?> entryA : mapA.entrySet()) {
        Object keyA = entryA.getKey();
        Object valueA = entryA.getValue();
        boolean found = false;
        for (Map.Entry<?, ?> entryB : mapB.entrySet()) {
          Object keyB = entryB.getKey();
          if (pigeonDeepEquals(keyA, keyB)) {
            Object valueB = entryB.getValue();
            if (pigeonDeepEquals(valueA, valueB)) {
              found = true;
              break;
            } else {
              return false;
            }
          }
        }
        if (!found) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Double && b instanceof Double) {
      return pigeonDoubleEquals((double) a, (double) b);
    }
    if (a instanceof Float && b instanceof Float) {
      return pigeonFloatEquals((float) a, (float) b);
    }
    return a.equals(b);
  }

  static int pigeonDeepHashCode(Object value) {
    if (value == null) { return 0; }
    if (value instanceof byte[]) {
      return Arrays.hashCode((byte[]) value);
    }
    if (value instanceof int[]) {
      return Arrays.hashCode((int[]) value);
    }
    if (value instanceof long[]) {
      return Arrays.hashCode((long[]) value);
    }
    if (value instanceof double[]) {
      double[] da = (double[]) value;
      int result = 1;
      for (double d : da) {
        result = 31 * result + pigeonDoubleHashCode(d);
      }
      return result;
    }
    if (value instanceof List) {
      int result = 1;
      for (Object item : (List<?>) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Map) {
      int result = 0;
      for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
        result += ((pigeonDeepHashCode(entry.getKey()) * 31) ^ pigeonDeepHashCode(entry.getValue()));
      }
      return result;
    }
    if (value instanceof Object[]) {
      int result = 1;
      for (Object item : (Object[]) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Double) {
      return pigeonDoubleHashCode((double) value);
    }
    if (value instanceof Float) {
      return pigeonFloatHashCode((float) value);
    }
    return value.hashCode();
  }


  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @NonNull
  protected static FlutterError createConnectionError(@NonNull String channelName) {
    return new FlutterError("channel-error",  "Unable to establish connection on channel: " + channelName + ".", "");
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  public enum ThermalPigeonConnectionType {
    BLUETOOTH(0),
    USB(1),
    TCP(2);

    final int index;

    ThermalPigeonConnectionType(final int index) {
      this.index = index;
    }
  }

  public enum ThermalPigeonPermissionState {
    GRANTED(0),
    DENIED(1),
    PERMANENTLY_DENIED(2),
    ACTIVITY_UNAVAILABLE(3),
    UNSUPPORTED(4);

    final int index;

    ThermalPigeonPermissionState(final int index) {
      this.index = index;
    }
  }

  public enum ThermalPigeonResultStatus {
    SUBMITTED(0),
    SETUP_REQUIRED(1),
    PERMISSION_DENIED(2),
    DEVICE_UNAVAILABLE(3),
    CONNECTION_FAILED(4),
    INVALID_REQUEST(5),
    INVALID_PDF(6),
    RASTERIZATION_FAILED(7),
    BUSY(8),
    NATIVE_FAILURE(9);

    final int index;

    ThermalPigeonResultStatus(final int index) {
      this.index = index;
    }
  }

  public enum ThermalPigeonProgressPhase {
    PREPARING(0),
    CONNECTING(1),
    RASTERIZING(2),
    TRANSMITTING(3),
    PRINTING(4);

    final int index;

    ThermalPigeonProgressPhase(final int index) {
      this.index = index;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class _Config {
    private @NonNull String sentinel;

    public @NonNull String getSentinel() {
      return sentinel;
    }

    public void setSentinel(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"sentinel\" is null.");
      }
      this.sentinel = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    _Config() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      _Config that = (_Config) o;
      return pigeonDeepEquals(sentinel, that.sentinel);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), sentinel};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String sentinel;

      @CanIgnoreReturnValue
      public @NonNull Builder setSentinel(@NonNull String setterArg) {
        this.sentinel = setterArg;
        return this;
      }

      public @NonNull _Config build() {
        _Config pigeonReturn = new _Config();
        pigeonReturn.setSentinel(sentinel);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(1);
      toListResult.add(sentinel);
      return toListResult;
    }

    static @NonNull _Config fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      _Config pigeonResult = new _Config();
      Object sentinel = pigeonVar_list.get(0);
      pigeonResult.setSentinel((String) sentinel);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ThermalPigeonDevice {
    private @NonNull String id;

    public @NonNull String getId() {
      return id;
    }

    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    private @NonNull ThermalPigeonConnectionType connectionType;

    public @NonNull ThermalPigeonConnectionType getConnectionType() {
      return connectionType;
    }

    public void setConnectionType(@NonNull ThermalPigeonConnectionType setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"connectionType\" is null.");
      }
      this.connectionType = setterArg;
    }

    private @NonNull String displayName;

    public @NonNull String getDisplayName() {
      return displayName;
    }

    public void setDisplayName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"displayName\" is null.");
      }
      this.displayName = setterArg;
    }

    private @Nullable String address;

    public @Nullable String getAddress() {
      return address;
    }

    public void setAddress(@Nullable String setterArg) {
      this.address = setterArg;
    }

    private @Nullable Long vendorId;

    public @Nullable Long getVendorId() {
      return vendorId;
    }

    public void setVendorId(@Nullable Long setterArg) {
      this.vendorId = setterArg;
    }

    private @Nullable Long productId;

    public @Nullable Long getProductId() {
      return productId;
    }

    public void setProductId(@Nullable Long setterArg) {
      this.productId = setterArg;
    }

    private @Nullable String serialNumber;

    public @Nullable String getSerialNumber() {
      return serialNumber;
    }

    public void setSerialNumber(@Nullable String setterArg) {
      this.serialNumber = setterArg;
    }

    private @Nullable String deviceName;

    public @Nullable String getDeviceName() {
      return deviceName;
    }

    public void setDeviceName(@Nullable String setterArg) {
      this.deviceName = setterArg;
    }

    private @NonNull Boolean preferred;

    public @NonNull Boolean getPreferred() {
      return preferred;
    }

    public void setPreferred(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"preferred\" is null.");
      }
      this.preferred = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ThermalPigeonDevice() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ThermalPigeonDevice that = (ThermalPigeonDevice) o;
      return pigeonDeepEquals(id, that.id) && pigeonDeepEquals(connectionType, that.connectionType) && pigeonDeepEquals(displayName, that.displayName) && pigeonDeepEquals(address, that.address) && pigeonDeepEquals(vendorId, that.vendorId) && pigeonDeepEquals(productId, that.productId) && pigeonDeepEquals(serialNumber, that.serialNumber) && pigeonDeepEquals(deviceName, that.deviceName) && pigeonDeepEquals(preferred, that.preferred);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), id, connectionType, displayName, address, vendorId, productId, serialNumber, deviceName, preferred};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable ThermalPigeonConnectionType connectionType;

      @CanIgnoreReturnValue
      public @NonNull Builder setConnectionType(@NonNull ThermalPigeonConnectionType setterArg) {
        this.connectionType = setterArg;
        return this;
      }

      private @Nullable String displayName;

      @CanIgnoreReturnValue
      public @NonNull Builder setDisplayName(@NonNull String setterArg) {
        this.displayName = setterArg;
        return this;
      }

      private @Nullable String address;

      @CanIgnoreReturnValue
      public @NonNull Builder setAddress(@Nullable String setterArg) {
        this.address = setterArg;
        return this;
      }

      private @Nullable Long vendorId;

      @CanIgnoreReturnValue
      public @NonNull Builder setVendorId(@Nullable Long setterArg) {
        this.vendorId = setterArg;
        return this;
      }

      private @Nullable Long productId;

      @CanIgnoreReturnValue
      public @NonNull Builder setProductId(@Nullable Long setterArg) {
        this.productId = setterArg;
        return this;
      }

      private @Nullable String serialNumber;

      @CanIgnoreReturnValue
      public @NonNull Builder setSerialNumber(@Nullable String setterArg) {
        this.serialNumber = setterArg;
        return this;
      }

      private @Nullable String deviceName;

      @CanIgnoreReturnValue
      public @NonNull Builder setDeviceName(@Nullable String setterArg) {
        this.deviceName = setterArg;
        return this;
      }

      private @Nullable Boolean preferred;

      @CanIgnoreReturnValue
      public @NonNull Builder setPreferred(@NonNull Boolean setterArg) {
        this.preferred = setterArg;
        return this;
      }

      public @NonNull ThermalPigeonDevice build() {
        ThermalPigeonDevice pigeonReturn = new ThermalPigeonDevice();
        pigeonReturn.setId(id);
        pigeonReturn.setConnectionType(connectionType);
        pigeonReturn.setDisplayName(displayName);
        pigeonReturn.setAddress(address);
        pigeonReturn.setVendorId(vendorId);
        pigeonReturn.setProductId(productId);
        pigeonReturn.setSerialNumber(serialNumber);
        pigeonReturn.setDeviceName(deviceName);
        pigeonReturn.setPreferred(preferred);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(9);
      toListResult.add(id);
      toListResult.add(connectionType);
      toListResult.add(displayName);
      toListResult.add(address);
      toListResult.add(vendorId);
      toListResult.add(productId);
      toListResult.add(serialNumber);
      toListResult.add(deviceName);
      toListResult.add(preferred);
      return toListResult;
    }

    static @NonNull ThermalPigeonDevice fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ThermalPigeonDevice pigeonResult = new ThermalPigeonDevice();
      Object id = pigeonVar_list.get(0);
      pigeonResult.setId((String) id);
      Object connectionType = pigeonVar_list.get(1);
      pigeonResult.setConnectionType((ThermalPigeonConnectionType) connectionType);
      Object displayName = pigeonVar_list.get(2);
      pigeonResult.setDisplayName((String) displayName);
      Object address = pigeonVar_list.get(3);
      pigeonResult.setAddress((String) address);
      Object vendorId = pigeonVar_list.get(4);
      pigeonResult.setVendorId((Long) vendorId);
      Object productId = pigeonVar_list.get(5);
      pigeonResult.setProductId((Long) productId);
      Object serialNumber = pigeonVar_list.get(6);
      pigeonResult.setSerialNumber((String) serialNumber);
      Object deviceName = pigeonVar_list.get(7);
      pigeonResult.setDeviceName((String) deviceName);
      Object preferred = pigeonVar_list.get(8);
      pigeonResult.setPreferred((Boolean) preferred);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ThermalPigeonProfile {
    private @NonNull String displayName;

    public @NonNull String getDisplayName() {
      return displayName;
    }

    public void setDisplayName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"displayName\" is null.");
      }
      this.displayName = setterArg;
    }

    private @NonNull ThermalPigeonConnectionType connectionType;

    public @NonNull ThermalPigeonConnectionType getConnectionType() {
      return connectionType;
    }

    public void setConnectionType(@NonNull ThermalPigeonConnectionType setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"connectionType\" is null.");
      }
      this.connectionType = setterArg;
    }

    private @NonNull Long printableWidthPx;

    public @NonNull Long getPrintableWidthPx() {
      return printableWidthPx;
    }

    public void setPrintableWidthPx(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"printableWidthPx\" is null.");
      }
      this.printableWidthPx = setterArg;
    }

    private @Nullable String bluetoothAddress;

    public @Nullable String getBluetoothAddress() {
      return bluetoothAddress;
    }

    public void setBluetoothAddress(@Nullable String setterArg) {
      this.bluetoothAddress = setterArg;
    }

    private @Nullable Long usbVendorId;

    public @Nullable Long getUsbVendorId() {
      return usbVendorId;
    }

    public void setUsbVendorId(@Nullable Long setterArg) {
      this.usbVendorId = setterArg;
    }

    private @Nullable Long usbProductId;

    public @Nullable Long getUsbProductId() {
      return usbProductId;
    }

    public void setUsbProductId(@Nullable Long setterArg) {
      this.usbProductId = setterArg;
    }

    private @Nullable String usbSerialNumber;

    public @Nullable String getUsbSerialNumber() {
      return usbSerialNumber;
    }

    public void setUsbSerialNumber(@Nullable String setterArg) {
      this.usbSerialNumber = setterArg;
    }

    private @Nullable String usbDeviceName;

    public @Nullable String getUsbDeviceName() {
      return usbDeviceName;
    }

    public void setUsbDeviceName(@Nullable String setterArg) {
      this.usbDeviceName = setterArg;
    }

    private @Nullable String tcpHost;

    public @Nullable String getTcpHost() {
      return tcpHost;
    }

    public void setTcpHost(@Nullable String setterArg) {
      this.tcpHost = setterArg;
    }

    private @Nullable Long tcpPort;

    public @Nullable Long getTcpPort() {
      return tcpPort;
    }

    public void setTcpPort(@Nullable Long setterArg) {
      this.tcpPort = setterArg;
    }

    private @NonNull Long tcpTimeoutSeconds;

    public @NonNull Long getTcpTimeoutSeconds() {
      return tcpTimeoutSeconds;
    }

    public void setTcpTimeoutSeconds(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"tcpTimeoutSeconds\" is null.");
      }
      this.tcpTimeoutSeconds = setterArg;
    }

    private @NonNull Long copies;

    public @NonNull Long getCopies() {
      return copies;
    }

    public void setCopies(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"copies\" is null.");
      }
      this.copies = setterArg;
    }

    private @NonNull Boolean gradient;

    public @NonNull Boolean getGradient() {
      return gradient;
    }

    public void setGradient(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"gradient\" is null.");
      }
      this.gradient = setterArg;
    }

    private @NonNull Long feedDots;

    public @NonNull Long getFeedDots() {
      return feedDots;
    }

    public void setFeedDots(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"feedDots\" is null.");
      }
      this.feedDots = setterArg;
    }

    private @NonNull Boolean cutAfterPrint;

    public @NonNull Boolean getCutAfterPrint() {
      return cutAfterPrint;
    }

    public void setCutAfterPrint(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"cutAfterPrint\" is null.");
      }
      this.cutAfterPrint = setterArg;
    }

    private @NonNull Boolean useEscAsteriskCommand;

    public @NonNull Boolean getUseEscAsteriskCommand() {
      return useEscAsteriskCommand;
    }

    public void setUseEscAsteriskCommand(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"useEscAsteriskCommand\" is null.");
      }
      this.useEscAsteriskCommand = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ThermalPigeonProfile() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ThermalPigeonProfile that = (ThermalPigeonProfile) o;
      return pigeonDeepEquals(displayName, that.displayName) && pigeonDeepEquals(connectionType, that.connectionType) && pigeonDeepEquals(printableWidthPx, that.printableWidthPx) && pigeonDeepEquals(bluetoothAddress, that.bluetoothAddress) && pigeonDeepEquals(usbVendorId, that.usbVendorId) && pigeonDeepEquals(usbProductId, that.usbProductId) && pigeonDeepEquals(usbSerialNumber, that.usbSerialNumber) && pigeonDeepEquals(usbDeviceName, that.usbDeviceName) && pigeonDeepEquals(tcpHost, that.tcpHost) && pigeonDeepEquals(tcpPort, that.tcpPort) && pigeonDeepEquals(tcpTimeoutSeconds, that.tcpTimeoutSeconds) && pigeonDeepEquals(copies, that.copies) && pigeonDeepEquals(gradient, that.gradient) && pigeonDeepEquals(feedDots, that.feedDots) && pigeonDeepEquals(cutAfterPrint, that.cutAfterPrint) && pigeonDeepEquals(useEscAsteriskCommand, that.useEscAsteriskCommand);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), displayName, connectionType, printableWidthPx, bluetoothAddress, usbVendorId, usbProductId, usbSerialNumber, usbDeviceName, tcpHost, tcpPort, tcpTimeoutSeconds, copies, gradient, feedDots, cutAfterPrint, useEscAsteriskCommand};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String displayName;

      @CanIgnoreReturnValue
      public @NonNull Builder setDisplayName(@NonNull String setterArg) {
        this.displayName = setterArg;
        return this;
      }

      private @Nullable ThermalPigeonConnectionType connectionType;

      @CanIgnoreReturnValue
      public @NonNull Builder setConnectionType(@NonNull ThermalPigeonConnectionType setterArg) {
        this.connectionType = setterArg;
        return this;
      }

      private @Nullable Long printableWidthPx;

      @CanIgnoreReturnValue
      public @NonNull Builder setPrintableWidthPx(@NonNull Long setterArg) {
        this.printableWidthPx = setterArg;
        return this;
      }

      private @Nullable String bluetoothAddress;

      @CanIgnoreReturnValue
      public @NonNull Builder setBluetoothAddress(@Nullable String setterArg) {
        this.bluetoothAddress = setterArg;
        return this;
      }

      private @Nullable Long usbVendorId;

      @CanIgnoreReturnValue
      public @NonNull Builder setUsbVendorId(@Nullable Long setterArg) {
        this.usbVendorId = setterArg;
        return this;
      }

      private @Nullable Long usbProductId;

      @CanIgnoreReturnValue
      public @NonNull Builder setUsbProductId(@Nullable Long setterArg) {
        this.usbProductId = setterArg;
        return this;
      }

      private @Nullable String usbSerialNumber;

      @CanIgnoreReturnValue
      public @NonNull Builder setUsbSerialNumber(@Nullable String setterArg) {
        this.usbSerialNumber = setterArg;
        return this;
      }

      private @Nullable String usbDeviceName;

      @CanIgnoreReturnValue
      public @NonNull Builder setUsbDeviceName(@Nullable String setterArg) {
        this.usbDeviceName = setterArg;
        return this;
      }

      private @Nullable String tcpHost;

      @CanIgnoreReturnValue
      public @NonNull Builder setTcpHost(@Nullable String setterArg) {
        this.tcpHost = setterArg;
        return this;
      }

      private @Nullable Long tcpPort;

      @CanIgnoreReturnValue
      public @NonNull Builder setTcpPort(@Nullable Long setterArg) {
        this.tcpPort = setterArg;
        return this;
      }

      private @Nullable Long tcpTimeoutSeconds;

      @CanIgnoreReturnValue
      public @NonNull Builder setTcpTimeoutSeconds(@NonNull Long setterArg) {
        this.tcpTimeoutSeconds = setterArg;
        return this;
      }

      private @Nullable Long copies;

      @CanIgnoreReturnValue
      public @NonNull Builder setCopies(@NonNull Long setterArg) {
        this.copies = setterArg;
        return this;
      }

      private @Nullable Boolean gradient;

      @CanIgnoreReturnValue
      public @NonNull Builder setGradient(@NonNull Boolean setterArg) {
        this.gradient = setterArg;
        return this;
      }

      private @Nullable Long feedDots;

      @CanIgnoreReturnValue
      public @NonNull Builder setFeedDots(@NonNull Long setterArg) {
        this.feedDots = setterArg;
        return this;
      }

      private @Nullable Boolean cutAfterPrint;

      @CanIgnoreReturnValue
      public @NonNull Builder setCutAfterPrint(@NonNull Boolean setterArg) {
        this.cutAfterPrint = setterArg;
        return this;
      }

      private @Nullable Boolean useEscAsteriskCommand;

      @CanIgnoreReturnValue
      public @NonNull Builder setUseEscAsteriskCommand(@NonNull Boolean setterArg) {
        this.useEscAsteriskCommand = setterArg;
        return this;
      }

      public @NonNull ThermalPigeonProfile build() {
        ThermalPigeonProfile pigeonReturn = new ThermalPigeonProfile();
        pigeonReturn.setDisplayName(displayName);
        pigeonReturn.setConnectionType(connectionType);
        pigeonReturn.setPrintableWidthPx(printableWidthPx);
        pigeonReturn.setBluetoothAddress(bluetoothAddress);
        pigeonReturn.setUsbVendorId(usbVendorId);
        pigeonReturn.setUsbProductId(usbProductId);
        pigeonReturn.setUsbSerialNumber(usbSerialNumber);
        pigeonReturn.setUsbDeviceName(usbDeviceName);
        pigeonReturn.setTcpHost(tcpHost);
        pigeonReturn.setTcpPort(tcpPort);
        pigeonReturn.setTcpTimeoutSeconds(tcpTimeoutSeconds);
        pigeonReturn.setCopies(copies);
        pigeonReturn.setGradient(gradient);
        pigeonReturn.setFeedDots(feedDots);
        pigeonReturn.setCutAfterPrint(cutAfterPrint);
        pigeonReturn.setUseEscAsteriskCommand(useEscAsteriskCommand);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(16);
      toListResult.add(displayName);
      toListResult.add(connectionType);
      toListResult.add(printableWidthPx);
      toListResult.add(bluetoothAddress);
      toListResult.add(usbVendorId);
      toListResult.add(usbProductId);
      toListResult.add(usbSerialNumber);
      toListResult.add(usbDeviceName);
      toListResult.add(tcpHost);
      toListResult.add(tcpPort);
      toListResult.add(tcpTimeoutSeconds);
      toListResult.add(copies);
      toListResult.add(gradient);
      toListResult.add(feedDots);
      toListResult.add(cutAfterPrint);
      toListResult.add(useEscAsteriskCommand);
      return toListResult;
    }

    static @NonNull ThermalPigeonProfile fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ThermalPigeonProfile pigeonResult = new ThermalPigeonProfile();
      Object displayName = pigeonVar_list.get(0);
      pigeonResult.setDisplayName((String) displayName);
      Object connectionType = pigeonVar_list.get(1);
      pigeonResult.setConnectionType((ThermalPigeonConnectionType) connectionType);
      Object printableWidthPx = pigeonVar_list.get(2);
      pigeonResult.setPrintableWidthPx((Long) printableWidthPx);
      Object bluetoothAddress = pigeonVar_list.get(3);
      pigeonResult.setBluetoothAddress((String) bluetoothAddress);
      Object usbVendorId = pigeonVar_list.get(4);
      pigeonResult.setUsbVendorId((Long) usbVendorId);
      Object usbProductId = pigeonVar_list.get(5);
      pigeonResult.setUsbProductId((Long) usbProductId);
      Object usbSerialNumber = pigeonVar_list.get(6);
      pigeonResult.setUsbSerialNumber((String) usbSerialNumber);
      Object usbDeviceName = pigeonVar_list.get(7);
      pigeonResult.setUsbDeviceName((String) usbDeviceName);
      Object tcpHost = pigeonVar_list.get(8);
      pigeonResult.setTcpHost((String) tcpHost);
      Object tcpPort = pigeonVar_list.get(9);
      pigeonResult.setTcpPort((Long) tcpPort);
      Object tcpTimeoutSeconds = pigeonVar_list.get(10);
      pigeonResult.setTcpTimeoutSeconds((Long) tcpTimeoutSeconds);
      Object copies = pigeonVar_list.get(11);
      pigeonResult.setCopies((Long) copies);
      Object gradient = pigeonVar_list.get(12);
      pigeonResult.setGradient((Boolean) gradient);
      Object feedDots = pigeonVar_list.get(13);
      pigeonResult.setFeedDots((Long) feedDots);
      Object cutAfterPrint = pigeonVar_list.get(14);
      pigeonResult.setCutAfterPrint((Boolean) cutAfterPrint);
      Object useEscAsteriskCommand = pigeonVar_list.get(15);
      pigeonResult.setUseEscAsteriskCommand((Boolean) useEscAsteriskCommand);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ThermalPigeonPrintRequest {
    private @NonNull String jobId;

    public @NonNull String getJobId() {
      return jobId;
    }

    public void setJobId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"jobId\" is null.");
      }
      this.jobId = setterArg;
    }

    private @NonNull String pdfPath;

    public @NonNull String getPdfPath() {
      return pdfPath;
    }

    public void setPdfPath(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"pdfPath\" is null.");
      }
      this.pdfPath = setterArg;
    }

    private @NonNull ThermalPigeonProfile profile;

    public @NonNull ThermalPigeonProfile getProfile() {
      return profile;
    }

    public void setProfile(@NonNull ThermalPigeonProfile setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"profile\" is null.");
      }
      this.profile = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ThermalPigeonPrintRequest() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ThermalPigeonPrintRequest that = (ThermalPigeonPrintRequest) o;
      return pigeonDeepEquals(jobId, that.jobId) && pigeonDeepEquals(pdfPath, that.pdfPath) && pigeonDeepEquals(profile, that.profile);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), jobId, pdfPath, profile};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String jobId;

      @CanIgnoreReturnValue
      public @NonNull Builder setJobId(@NonNull String setterArg) {
        this.jobId = setterArg;
        return this;
      }

      private @Nullable String pdfPath;

      @CanIgnoreReturnValue
      public @NonNull Builder setPdfPath(@NonNull String setterArg) {
        this.pdfPath = setterArg;
        return this;
      }

      private @Nullable ThermalPigeonProfile profile;

      @CanIgnoreReturnValue
      public @NonNull Builder setProfile(@NonNull ThermalPigeonProfile setterArg) {
        this.profile = setterArg;
        return this;
      }

      public @NonNull ThermalPigeonPrintRequest build() {
        ThermalPigeonPrintRequest pigeonReturn = new ThermalPigeonPrintRequest();
        pigeonReturn.setJobId(jobId);
        pigeonReturn.setPdfPath(pdfPath);
        pigeonReturn.setProfile(profile);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(jobId);
      toListResult.add(pdfPath);
      toListResult.add(profile);
      return toListResult;
    }

    static @NonNull ThermalPigeonPrintRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ThermalPigeonPrintRequest pigeonResult = new ThermalPigeonPrintRequest();
      Object jobId = pigeonVar_list.get(0);
      pigeonResult.setJobId((String) jobId);
      Object pdfPath = pigeonVar_list.get(1);
      pigeonResult.setPdfPath((String) pdfPath);
      Object profile = pigeonVar_list.get(2);
      pigeonResult.setProfile((ThermalPigeonProfile) profile);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ThermalPigeonResult {
    private @NonNull ThermalPigeonResultStatus status;

    public @NonNull ThermalPigeonResultStatus getStatus() {
      return status;
    }

    public void setStatus(@NonNull ThermalPigeonResultStatus setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"status\" is null.");
      }
      this.status = setterArg;
    }

    private @Nullable String errorCode;

    public @Nullable String getErrorCode() {
      return errorCode;
    }

    public void setErrorCode(@Nullable String setterArg) {
      this.errorCode = setterArg;
    }

    private @Nullable String diagnostic;

    public @Nullable String getDiagnostic() {
      return diagnostic;
    }

    public void setDiagnostic(@Nullable String setterArg) {
      this.diagnostic = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ThermalPigeonResult() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ThermalPigeonResult that = (ThermalPigeonResult) o;
      return pigeonDeepEquals(status, that.status) && pigeonDeepEquals(errorCode, that.errorCode) && pigeonDeepEquals(diagnostic, that.diagnostic);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), status, errorCode, diagnostic};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable ThermalPigeonResultStatus status;

      @CanIgnoreReturnValue
      public @NonNull Builder setStatus(@NonNull ThermalPigeonResultStatus setterArg) {
        this.status = setterArg;
        return this;
      }

      private @Nullable String errorCode;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorCode(@Nullable String setterArg) {
        this.errorCode = setterArg;
        return this;
      }

      private @Nullable String diagnostic;

      @CanIgnoreReturnValue
      public @NonNull Builder setDiagnostic(@Nullable String setterArg) {
        this.diagnostic = setterArg;
        return this;
      }

      public @NonNull ThermalPigeonResult build() {
        ThermalPigeonResult pigeonReturn = new ThermalPigeonResult();
        pigeonReturn.setStatus(status);
        pigeonReturn.setErrorCode(errorCode);
        pigeonReturn.setDiagnostic(diagnostic);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(status);
      toListResult.add(errorCode);
      toListResult.add(diagnostic);
      return toListResult;
    }

    static @NonNull ThermalPigeonResult fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ThermalPigeonResult pigeonResult = new ThermalPigeonResult();
      Object status = pigeonVar_list.get(0);
      pigeonResult.setStatus((ThermalPigeonResultStatus) status);
      Object errorCode = pigeonVar_list.get(1);
      pigeonResult.setErrorCode((String) errorCode);
      Object diagnostic = pigeonVar_list.get(2);
      pigeonResult.setDiagnostic((String) diagnostic);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ThermalPigeonProgress {
    private @NonNull String jobId;

    public @NonNull String getJobId() {
      return jobId;
    }

    public void setJobId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"jobId\" is null.");
      }
      this.jobId = setterArg;
    }

    private @NonNull ThermalPigeonProgressPhase phase;

    public @NonNull ThermalPigeonProgressPhase getPhase() {
      return phase;
    }

    public void setPhase(@NonNull ThermalPigeonProgressPhase setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"phase\" is null.");
      }
      this.phase = setterArg;
    }

    private @Nullable Long copyIndex;

    public @Nullable Long getCopyIndex() {
      return copyIndex;
    }

    public void setCopyIndex(@Nullable Long setterArg) {
      this.copyIndex = setterArg;
    }

    private @Nullable Long copyCount;

    public @Nullable Long getCopyCount() {
      return copyCount;
    }

    public void setCopyCount(@Nullable Long setterArg) {
      this.copyCount = setterArg;
    }

    private @Nullable Long pageIndex;

    public @Nullable Long getPageIndex() {
      return pageIndex;
    }

    public void setPageIndex(@Nullable Long setterArg) {
      this.pageIndex = setterArg;
    }

    private @Nullable Long pageCount;

    public @Nullable Long getPageCount() {
      return pageCount;
    }

    public void setPageCount(@Nullable Long setterArg) {
      this.pageCount = setterArg;
    }

    private @Nullable Long bytesSent;

    public @Nullable Long getBytesSent() {
      return bytesSent;
    }

    public void setBytesSent(@Nullable Long setterArg) {
      this.bytesSent = setterArg;
    }

    private @Nullable Long totalBytes;

    public @Nullable Long getTotalBytes() {
      return totalBytes;
    }

    public void setTotalBytes(@Nullable Long setterArg) {
      this.totalBytes = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ThermalPigeonProgress() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ThermalPigeonProgress that = (ThermalPigeonProgress) o;
      return pigeonDeepEquals(jobId, that.jobId) && pigeonDeepEquals(phase, that.phase) && pigeonDeepEquals(copyIndex, that.copyIndex) && pigeonDeepEquals(copyCount, that.copyCount) && pigeonDeepEquals(pageIndex, that.pageIndex) && pigeonDeepEquals(pageCount, that.pageCount) && pigeonDeepEquals(bytesSent, that.bytesSent) && pigeonDeepEquals(totalBytes, that.totalBytes);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), jobId, phase, copyIndex, copyCount, pageIndex, pageCount, bytesSent, totalBytes};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String jobId;

      @CanIgnoreReturnValue
      public @NonNull Builder setJobId(@NonNull String setterArg) {
        this.jobId = setterArg;
        return this;
      }

      private @Nullable ThermalPigeonProgressPhase phase;

      @CanIgnoreReturnValue
      public @NonNull Builder setPhase(@NonNull ThermalPigeonProgressPhase setterArg) {
        this.phase = setterArg;
        return this;
      }

      private @Nullable Long copyIndex;

      @CanIgnoreReturnValue
      public @NonNull Builder setCopyIndex(@Nullable Long setterArg) {
        this.copyIndex = setterArg;
        return this;
      }

      private @Nullable Long copyCount;

      @CanIgnoreReturnValue
      public @NonNull Builder setCopyCount(@Nullable Long setterArg) {
        this.copyCount = setterArg;
        return this;
      }

      private @Nullable Long pageIndex;

      @CanIgnoreReturnValue
      public @NonNull Builder setPageIndex(@Nullable Long setterArg) {
        this.pageIndex = setterArg;
        return this;
      }

      private @Nullable Long pageCount;

      @CanIgnoreReturnValue
      public @NonNull Builder setPageCount(@Nullable Long setterArg) {
        this.pageCount = setterArg;
        return this;
      }

      private @Nullable Long bytesSent;

      @CanIgnoreReturnValue
      public @NonNull Builder setBytesSent(@Nullable Long setterArg) {
        this.bytesSent = setterArg;
        return this;
      }

      private @Nullable Long totalBytes;

      @CanIgnoreReturnValue
      public @NonNull Builder setTotalBytes(@Nullable Long setterArg) {
        this.totalBytes = setterArg;
        return this;
      }

      public @NonNull ThermalPigeonProgress build() {
        ThermalPigeonProgress pigeonReturn = new ThermalPigeonProgress();
        pigeonReturn.setJobId(jobId);
        pigeonReturn.setPhase(phase);
        pigeonReturn.setCopyIndex(copyIndex);
        pigeonReturn.setCopyCount(copyCount);
        pigeonReturn.setPageIndex(pageIndex);
        pigeonReturn.setPageCount(pageCount);
        pigeonReturn.setBytesSent(bytesSent);
        pigeonReturn.setTotalBytes(totalBytes);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(8);
      toListResult.add(jobId);
      toListResult.add(phase);
      toListResult.add(copyIndex);
      toListResult.add(copyCount);
      toListResult.add(pageIndex);
      toListResult.add(pageCount);
      toListResult.add(bytesSent);
      toListResult.add(totalBytes);
      return toListResult;
    }

    static @NonNull ThermalPigeonProgress fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ThermalPigeonProgress pigeonResult = new ThermalPigeonProgress();
      Object jobId = pigeonVar_list.get(0);
      pigeonResult.setJobId((String) jobId);
      Object phase = pigeonVar_list.get(1);
      pigeonResult.setPhase((ThermalPigeonProgressPhase) phase);
      Object copyIndex = pigeonVar_list.get(2);
      pigeonResult.setCopyIndex((Long) copyIndex);
      Object copyCount = pigeonVar_list.get(3);
      pigeonResult.setCopyCount((Long) copyCount);
      Object pageIndex = pigeonVar_list.get(4);
      pigeonResult.setPageIndex((Long) pageIndex);
      Object pageCount = pigeonVar_list.get(5);
      pigeonResult.setPageCount((Long) pageCount);
      Object bytesSent = pigeonVar_list.get(6);
      pigeonResult.setBytesSent((Long) bytesSent);
      Object totalBytes = pigeonVar_list.get(7);
      pigeonResult.setTotalBytes((Long) totalBytes);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129: {
          Object value = readValue(buffer);
          return value == null ? null : ThermalPigeonConnectionType.values()[((Long) value).intValue()];
        }
        case (byte) 130: {
          Object value = readValue(buffer);
          return value == null ? null : ThermalPigeonPermissionState.values()[((Long) value).intValue()];
        }
        case (byte) 131: {
          Object value = readValue(buffer);
          return value == null ? null : ThermalPigeonResultStatus.values()[((Long) value).intValue()];
        }
        case (byte) 132: {
          Object value = readValue(buffer);
          return value == null ? null : ThermalPigeonProgressPhase.values()[((Long) value).intValue()];
        }
        case (byte) 133:
          return _Config.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 134:
          return ThermalPigeonDevice.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 135:
          return ThermalPigeonProfile.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 136:
          return ThermalPigeonPrintRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 137:
          return ThermalPigeonResult.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 138:
          return ThermalPigeonProgress.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof ThermalPigeonConnectionType) {
        stream.write(129);
        writeValue(stream, value == null ? null : ((ThermalPigeonConnectionType) value).index);
      } else if (value instanceof ThermalPigeonPermissionState) {
        stream.write(130);
        writeValue(stream, value == null ? null : ((ThermalPigeonPermissionState) value).index);
      } else if (value instanceof ThermalPigeonResultStatus) {
        stream.write(131);
        writeValue(stream, value == null ? null : ((ThermalPigeonResultStatus) value).index);
      } else if (value instanceof ThermalPigeonProgressPhase) {
        stream.write(132);
        writeValue(stream, value == null ? null : ((ThermalPigeonProgressPhase) value).index);
      } else if (value instanceof _Config) {
        stream.write(133);
        writeValue(stream, ((_Config) value).toList());
      } else if (value instanceof ThermalPigeonDevice) {
        stream.write(134);
        writeValue(stream, ((ThermalPigeonDevice) value).toList());
      } else if (value instanceof ThermalPigeonProfile) {
        stream.write(135);
        writeValue(stream, ((ThermalPigeonProfile) value).toList());
      } else if (value instanceof ThermalPigeonPrintRequest) {
        stream.write(136);
        writeValue(stream, ((ThermalPigeonPrintRequest) value).toList());
      } else if (value instanceof ThermalPigeonResult) {
        stream.write(137);
        writeValue(stream, ((ThermalPigeonResult) value).toList());
      } else if (value instanceof ThermalPigeonProgress) {
        stream.write(138);
        writeValue(stream, ((ThermalPigeonProgress) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface ThermalPrinterPermissionHostApi {

    void getBluetoothPermissionState(@NonNull Result<ThermalPigeonPermissionState> result);

    void requestBluetoothPermissions(@NonNull Result<ThermalPigeonPermissionState> result);

    void hasUsbPermission(@NonNull ThermalPigeonDevice device, @NonNull Result<ThermalPigeonPermissionState> result);

    void requestUsbPermission(@NonNull ThermalPigeonDevice device, @NonNull Result<ThermalPigeonPermissionState> result);

    /** The codec used by ThermalPrinterPermissionHostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `ThermalPrinterPermissionHostApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable ThermalPrinterPermissionHostApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable ThermalPrinterPermissionHostApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.reporting_bridge_flutter.ThermalPrinterPermissionHostApi.getBluetoothPermissionState" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<ThermalPigeonPermissionState> resultCallback =
                    new Result<ThermalPigeonPermissionState>() {
                      public void success(ThermalPigeonPermissionState result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getBluetoothPermissionState(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.reporting_bridge_flutter.ThermalPrinterPermissionHostApi.requestBluetoothPermissions" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<ThermalPigeonPermissionState> resultCallback =
                    new Result<ThermalPigeonPermissionState>() {
                      public void success(ThermalPigeonPermissionState result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.requestBluetoothPermissions(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.reporting_bridge_flutter.ThermalPrinterPermissionHostApi.hasUsbPermission" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                ThermalPigeonDevice deviceArg = (ThermalPigeonDevice) args.get(0);
                Result<ThermalPigeonPermissionState> resultCallback =
                    new Result<ThermalPigeonPermissionState>() {
                      public void success(ThermalPigeonPermissionState result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.hasUsbPermission(deviceArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.reporting_bridge_flutter.ThermalPrinterPermissionHostApi.requestUsbPermission" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                ThermalPigeonDevice deviceArg = (ThermalPigeonDevice) args.get(0);
                Result<ThermalPigeonPermissionState> resultCallback =
                    new Result<ThermalPigeonPermissionState>() {
                      public void success(ThermalPigeonPermissionState result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.requestUsbPermission(deviceArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface ThermalPrinterHostApi {

    void listPairedBluetoothDevices(@NonNull Result<List<ThermalPigeonDevice>> result);

    void listConnectedUsbPrinters(@NonNull Result<List<ThermalPigeonDevice>> result);

    void printPdf(@NonNull ThermalPigeonPrintRequest request, @NonNull Result<ThermalPigeonResult> result);

    /** The codec used by ThermalPrinterHostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `ThermalPrinterHostApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable ThermalPrinterHostApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable ThermalPrinterHostApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.reporting_bridge_flutter.ThermalPrinterHostApi.listPairedBluetoothDevices" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<List<ThermalPigeonDevice>> resultCallback =
                    new Result<List<ThermalPigeonDevice>>() {
                      public void success(List<ThermalPigeonDevice> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.listPairedBluetoothDevices(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.reporting_bridge_flutter.ThermalPrinterHostApi.listConnectedUsbPrinters" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<List<ThermalPigeonDevice>> resultCallback =
                    new Result<List<ThermalPigeonDevice>>() {
                      public void success(List<ThermalPigeonDevice> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.listConnectedUsbPrinters(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.reporting_bridge_flutter.ThermalPrinterHostApi.printPdf" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                ThermalPigeonPrintRequest requestArg = (ThermalPigeonPrintRequest) args.get(0);
                Result<ThermalPigeonResult> resultCallback =
                    new Result<ThermalPigeonResult>() {
                      public void success(ThermalPigeonResult result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.printPdf(requestArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /** Generated class from Pigeon that represents Flutter messages that can be called from Java. */
  public static class ThermalPrinterFlutterApi {
    private final @NonNull BinaryMessenger binaryMessenger;
    private final String messageChannelSuffix;

    public ThermalPrinterFlutterApi(@NonNull BinaryMessenger argBinaryMessenger) {
      this(argBinaryMessenger, "");
    }
    public ThermalPrinterFlutterApi(@NonNull BinaryMessenger argBinaryMessenger, @NonNull String messageChannelSuffix) {
      this.binaryMessenger = argBinaryMessenger;
      this.messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
    }

    /**
     * Public interface for sending reply.
     * The codec used by ThermalPrinterFlutterApi.
     */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    public void onPrintProgress(@NonNull ThermalPigeonProgress progressArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.reporting_bridge_flutter.ThermalPrinterFlutterApi.onPrintProgress" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(progressArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
  }
}
